/**
 * Rebuild public/favicon.ico from public/favicon.svg.
 *
 * Run with `pnpm icons` after changing the mark, and commit the result.
 *
 * Why this exists: the .ico is the only icon on the site that cannot be
 * generated by the Next build. Every other size comes from src/lib/appIcon.tsx
 * at build time, so when the mark was redesigned they all moved and this one
 * did not — leaving the *previous* art (a near-black tile with thin cyan
 * strokes, invisible on a dark browser theme) in the tab of every client that
 * prefers .ico, and in Google's search results, which crawls /favicon.ico
 * directly and ignores the SVG.
 *
 * It is not wired into the build on purpose: it needs sharp's SVG rasteriser,
 * the output is a committed asset that changes roughly never, and `cf:build`
 * runs on every deploy.
 *
 * PNG-in-ICO rather than BMP. Every browser since IE11 reads it, it is a third
 * of the size, and it keeps real alpha instead of a 1-bit mask — which is what
 * the rounded corners of the tile need.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import sharp from 'sharp'

const PUBLIC_DIR = join(import.meta.dirname, '..', 'public')

// 16 and 32 are what a tab and a bookmark bar ask for; 48 is what Windows uses
// for shortcuts and what Google's crawler prefers. Above that, every client
// that matters has already picked favicon.svg.
const SIZES = [16, 32, 48]

const ICONDIR_BYTES = 6
const ICONDIRENTRY_BYTES = 16

/**
 * Assemble the ICO container: a 6-byte header, one 16-byte directory entry per
 * image, then the payloads. Offsets are absolute from the start of the file, so
 * they can only be computed once every entry's size is known.
 */
function buildIco(images) {
  const header = Buffer.alloc(ICONDIR_BYTES)
  header.writeUInt16LE(0, 0) // reserved
  header.writeUInt16LE(1, 2) // 1 = icon (2 would be a cursor)
  header.writeUInt16LE(images.length, 4)

  const directory = Buffer.alloc(ICONDIRENTRY_BYTES * images.length)
  let offset = ICONDIR_BYTES + directory.length

  images.forEach(({ size, data }, index) => {
    const at = index * ICONDIRENTRY_BYTES
    // 256 is stored as 0; nothing here is that large, but the encoding is the
    // reason these two fields are one byte each.
    directory.writeUInt8(size === 256 ? 0 : size, at)
    directory.writeUInt8(size === 256 ? 0 : size, at + 1)
    directory.writeUInt8(0, at + 2) // palette entries: none, this is truecolour
    directory.writeUInt8(0, at + 3) // reserved
    directory.writeUInt16LE(1, at + 4) // colour planes
    directory.writeUInt16LE(32, at + 6) // bits per pixel
    directory.writeUInt32LE(data.length, at + 8)
    directory.writeUInt32LE(offset, at + 12)
    offset += data.length
  })

  return Buffer.concat([header, directory, ...images.map((image) => image.data)])
}

const source = readFileSync(join(PUBLIC_DIR, 'favicon.svg'))

const images = await Promise.all(
  SIZES.map(async (size) => ({
    size,
    // `density` scales librsvg's rasterisation up before the resize, so the
    // rounded corners and the glyph edges are antialiased from a larger render
    // rather than from a 16px one.
    data: await sharp(source, { density: 72 * (size / 16) })
      .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .png({ compressionLevel: 9, effort: 10 })
      .toBuffer(),
  })),
)

const ico = buildIco(images)
writeFileSync(join(PUBLIC_DIR, 'favicon.ico'), ico)

console.log(
  `favicon.ico: ${images.map((i) => `${i.size}x${i.size}`).join(', ')} — ${ico.length} bytes`,
)
